version: "3"
services:
  redis:
    image: "redis:alpine"

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - ASIAN_ODDS_USER=${ASIAN_ODDS_USER}
      - ASIAN_ODDS_PWD=${ASIAN_ODDS_PWD}
      - ASIAN_ODDS_URL=${ASIAN_ODDS_URL}
      - STATISCS_URL=${STATISCS_URL}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
